version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-net

  mongodb-admin:
    image: mrvautin/adminmongo:latest
    restart: always
    ports:
      - 8082:8080
    environment:
      - ADMINMONGO_USERNAME=admin
      - ADMINMONGO_PASSWORD=password
    networks:
      - app-net
    depends_on:
      - mongodb

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - 3001:3001
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/blog
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    networks:
      - app-net

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - frontend
    networks:
      - app-net

volumes:
  mongodb_data:
  letsencrypt:

networks:
  app-net: