version: "3"

services:
  nginx:
    build:
      context: ./nginx_config
      dockerfile: nginx.Dockerfile
    image: nginx-proxy
  nobus_webadmin:
    build:
      context: ./nobus_webadmin
      dockerfile: admin.Dockerfile
    image: nobus-webadmin
  nobus_web:
    build:
      context: ./nobus_v2.0
      dockerfile: web.Dockerfile
    image: nobus-web
  nobus_blog:
    build:
      context: ./nobus_blog
      dockerfile: blog.Dockerfile
    image: nobus-blog
    
